/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: d1daf050f011aa424e5358f837842f46)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyContainer";
	}
	interface Env {
		MY_CONTAINER: DurableObjectNamespace<import("./src/index").MyContainer>;
	}
}
interface Env extends Cloudflare.Env {}
